spring.application.name=migrosOneLogistic
spring.profiles.active=dev
#spring.jpa.properties.hibernate.connection.url=jdbc:h2:mem:migrosone


#
# H2 Database Configuration
#
spring.datasource.url=jdbc:h2:mem:migrosone;MODE=PostgreSQL;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=migrosone
spring.datasource.password=migrosone
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create


